### ISSUE TITLE
[Enhancement] Use re-import to upload scans if there is a test existing. 

### ISSUE THREAD

**Issue by manuel-sommer** [telekom-mms/trivy-dojo-report-operator#33]
### Description

Could you enable a way to use reimport in case a test is already existing? 
https://defectdojo.github.io/django-DefectDojo/integrations/importing/#reimport

**Comment by rndmh3ro** [comment]
> Could you enable a way to use reimport in case a test is already existing?

Do you mean, when a new VulnerabilityReport gets created for an image that already had a report sent to dojo?
So then

**Comment by manuel-sommer** [comment]
Yes, exactly.

**Comment by rndmh3ro** [comment]
This sounds reasonable.

The docs state:

> If no existing Test is found, the reimport endpoint will use the import function to import the provided report into a new Test. This means a (CI/CD) script using the API doesn’t need to know if a Test already exist, or if it is a first time upload for this product / engagement.

So this probably means we just have to use the re-import-endpoint instead of the import-endpoint (and add the  do_not_reactivate-option), then it will just work.

**Comment by rndmh3ro** [comment]
This should be implemented in #34. Feel free to test and report any issues!
