### ISSUE TITLE
[Enhancement] Add more kind of reports and make them configurables

### ISSUE THREAD

**Issue by corvusmod** [telekom-mms/trivy-dojo-report-operator#52]
### Description

Currently, only vulnerability reports can be sent to DefectDojo. This is configured here: https://github.com/telekom-mms/trivy-dojo-report-operator/blob/ec52e330f3d6da1eb7026a48b4ee2625fc01daa7/src/handlers.py#L53C18-L53C61

But other reports can be sent, such as:
https://aquasecurity.github.io/trivy-operator/v0.18.3/docs/crds/

It would be great to add these reports to DD and configure which ones we want to send with a variable/value (in the helm chart). 

Other than that... thanks for this operator, it's working great.

**Comment by corvusmod** [comment]
![image](https://github.com/telekom-mms/trivy-dojo-report-operator/assets/734584/c7982727-0315-4fa5-ac24-efa18bcccf1f)

This is how a ConfigAuditReports is shown in DD

**Comment by corvusmod** [comment]
![image](https://github.com/telekom-mms/trivy-dojo-report-operator/assets/734584/845330d0-1812-4914-8d56-50689ba1b9ab)

And a RbacAssessmentReport

**Comment by rndmh3ro** [comment]
Awesome idea, @corvusmod, thank you for this. I agree that this would be very nice to have.

Some ideas:
- It should be configurable what reports to send to DefectDojo (with a default to send all)
- all report-CRDs should have the field `x-kubernetes-preserve-unknown-fields` set to true ([see](https://github.com/aquasecurity/trivy-operator/pull/1455/files)). This is needed so the operator can set annotations on the reports to know which one it already sent to DD. This is a change in the trivy-operator.
- we finally need some proper tests :)
-

**Comment by rndmh3ro** [comment]
I could not help myself and tried to implement it as an early version: https://github.com/telekom-mms/trivy-dojo-report-operator/tree/support_reports

To test it, you need to run the operator from the branch and export the REPORTS-variable like this:
```
export REPORTS=sbomreports,vulnerabilityreports,ConfigAuditReports
```

Basically a comma-separated list of reports.

Keep in mind that you will receive error-messages from the operator (`Patching failed with inconsistencies`) as long as `x-kubernetes-preserve-unknown-fields` is not set on the CRDs.

**Comment by rndmh3ro** [comment]
https://github.com/aquasecurity/trivy-operator/pull/1839

**Comment by corvusmod** [comment]
Hi

I see that you created a new version with the needed changes. Thanks. 
While testing it seems that the changes are working, but there is a problem with permissions in helm charts. No access to some resources.

I fixed it with that change:

`diff --git a/templates/rbac.yaml b/templates/rbac.yaml
index 1555487..598e7ea 100644
--- a/templates/rbac.yaml
+++ b/templates/rbac.yaml
@@ -18,6 +18,10 @@ rules:
   - aquasecurity.github.io
   resources:
   - vulnerabilityreports
+  - rbacassessmentreports
+  - configauditreports
+  - infraassessmentreports
+  - exposedsecretreports
   verbs:
   - list
   - watch`

**Comment by rndmh3ro** [comment]
Great catch, thanks! Do you want to create a PR to fix this?
