### ISSUE TITLE
[Enhancement] Separate Engagements by Namespace

### ISSUE THREAD

**Issue by teyhouse** [telekom-mms/trivy-dojo-report-operator#54]
### Description

Hey there,

would it be possible to create separate engagements based on namespaces and label them accordingly?
Right now the Findings from different Namespaces get mixed up into one ore more engagements without labels, making it hard to tell them apart.

Besides the Separation it would help to have the Namespace-Name added to the engagement name (like its part of the Service column already). Right now I can't distribute the findings to different teams, which kind of feels anti-pattern for DefectDojo.

Especially for bigger Orgs with different Teams per Namespace, this should be important.
Thanks for considering this!

![screen2](https://github.com/telekom-mms/trivy-dojo-report-operator/assets/828439/640a163f-de48-4f70-925a-6994a570bf0e)
![screen1](https://github.com/telekom-mms/trivy-dojo-report-operator/assets/828439/55e8c901-a931-49e3-b5cc-820356cec701)

**Comment by rndmh3ro** [comment]
Hi @teyhouse,

I *think* it is already possible to do this, see [here](https://github.com/telekom-mms/trivy-dojo-report-operator?tab=readme-ov-file#a-note-on-eval).

When defining this:

```
export DEFECT_DOJO_EVAL_ENGAGEMENT_NAME=true
export DEFECT_DOJO_ENGAGEMENT_NAME='meta["namespace"]'
```
I get this:

![image](https://github.com/telekom-mms/trivy-dojo-report-operator/assets/3198961/5c6ed619-bed9-4077-b2b0-6eea50eca0b9)


Note that you can only use user-defined values here `or` eval'd values. You cannot mix them.

So this is possible:

```
export DEFECT_DOJO_EVAL_ENGAGEMENT_NAME=true
export DEFECT_DOJO_ENGAGEMENT_NAME='meta["namespace"]'
```

But this is not:

```
export DEFECT_DOJO_EVAL_ENGAGEMENT_NAME=true
export DEFECT_DOJO_ENGAGEMENT_NAME='meta["namespace"]-test123'
```

Let me know what you think!

**Comment by teyhouse** [comment]
Solved.
