### ISSUE TITLE
[Question] Add Telekom to Trivy Adopters

### ISSUE THREAD

**Issue by AnaisUrlichs** [telekom-mms/trivy-dojo-report-operator#66]
### Question

Hi there, I just came across this project -- thank you, great work. I'm part of the open source team at Aqua Security and we were wondering whether you could add Telekom to our list of adopters? It takes 30sec to fill out the form and we would highly appreciate the support. It's on `Trivy Repo < Discussions < Adopters`: https://github.com/aquasecurity/trivy/discussions/categories/adopters

**Comment by rndmh3ro** [comment]
I'd love to, but I'm not authorized to do so and getting the permission takes weeks if not months (I tried).
