### ISSUE TITLE
[Enhancement] Publish new release with latest base images

### ISSUE THREAD

**Issue by quirinziessler** [telekom-mms/trivy-dojo-report-operator#72]
### Description

Right now the latest available version (0.6.2) has 130 open findings, 126 from the base image and 4 python packages. I attached the Trivy output to this issue.
Is it maybe possible for you to publish a newer version image with the latest base image? I see renovate is already running so would it maybe make sense to deploy the image on a weekly/monthly rhythm with the renovate PRs?

### Additional information

[trivy.txt](https://github.com/user-attachments/files/16413148/trivy.txt)

**Comment by rndmh3ro** [comment]
Thanks, done!

> I see renovate is already running so would it maybe make sense to deploy the image on a weekly/monthly rhythm with the renovate PRs?

With our current workflow it's only the press of a button to release a new version. I don't really want to spend any more effort on this. But feel free to propose something for this.
