### ISSUE TITLE
[Bug] Image docker-trivy-dojo-operator:0.7.3 does not exist?

### ISSUE THREAD

**Issue by tidusete** [telekom-mms/trivy-dojo-report-operator#82]
### Description

I'm not able to deploy the helmchart because I have the deployment on `ImagePullBackOff` because is not able to pull the image ghcr.io/telekom-mms/docker-trivy-dojo-operator:0.7.3

### Reproduction steps

Whenever you try to pull the image: 
```
➜ docker pull ghcr.io/telekom-mms/docker-trivy-dojo-operator:0.7.3

Error response from daemon: manifest unknown
```
If i try to pull the image on the version 0.7.2 it works:
```
➜ docker pull ghcr.io/telekom-mms/docker-trivy-dojo-operator:0.7.2

0.7.2: Pulling from telekom-mms/docker-trivy-dojo-operator
Digest: sha256:54a2950dffb5d0c8b9e7720fab2c1d0daae377c21eb4fbbbe456af9049f72a18
Status: Image is up to date for ghcr.io/telekom-mms/docker-trivy-dojo-operator:0.7.2
ghcr.io/telekom-mms/docker-trivy-dojo-operator:0.7.2
```

### Current Behavior

The deployment is stuck on ImagePullBackOff

### Expected Behavior

Have the deployment running

**Comment by rndmh3ro** [comment]
That's because there is no 0.7.3 release. Or rather was.. it exists now.
