### ISSUE TITLE
[Question] What parameters do you run this operator?

### ISSUE THREAD

**Issue by iamhalje** [telekom-mms/trivy-dojo-report-operator#85]
### Question

If a single instance of the operator is running, it is assumed that we will send the required data from the entire cluster to DefectDojo. Once a vulnerability is resolved, we will not delete the product and replace it with a new data scope. Instead, we need to change the default parameters to:

`defectDojoCloseOldFindings: true`
`defectDojoDoNotReactivate: false` (?)

![image](https://github.com/user-attachments/assets/5d00f69c-c7a3-419f-9fde-c2f4cc356aff)

However, in my case, all vulnerabilities are being closed, not just those specific to the service. This is how it looks. Maybe I’m doing something wrong, but I can’t pinpoint it. Could you please advise which parameters you use and in what scenarios for this operator?

I would also like to separately ask for help from @manuel-sommer. I often see your changes related to Trivy in DefectDojo. Perhaps you’ve encountered this issue before?

**Comment by manuel-sommer** [comment]
Hi @iamhalje, at the moment I am in a test phase and noticed multiple ways to improve the Trivy operator parser yet. I personally would try out defectDojoDoNotReactivate: true to always go forward. This could also improve the performance. But I not yet can't recommend parameters here, yet.

**Comment by iamhalje** [comment]
The main issue is that vulnerabilities that haven't been reported for a long time should be closed, but with the defectDojoCloseOldFindings parameter, all vulnerabilities are being closed, as shown in the screenshot, despite it stating "only the findings for this service will be closed."

I would also like to understand how to conveniently use it in this case. As far as I understand, this situation occurs because of re-importing, not because a new engagement is created for each request.

**Comment by iamhalje** [comment]
And yes, I can retrieve all vulnerabilities with the default parameters, but to review which ones are currently active, I need to delete the product so it gets recreated and populated again. This is the situation I'm facing. I would like the flag for closing vulnerabilities to work as described.

Therefore, I think I might be doing something wrong on my side. If everything is working correctly for you and this issue doesn’t occur, please let me know.

**Comment by iamhalje** [comment]
![image](https://github.com/user-attachments/assets/8a9dabdd-e34e-4990-807f-3ea5b39deb7d)

`cert-manager/ReplicaSet/cert-manager-webhook-7d977f6f7`

Only one appeared in these tests, but it's clear that all were eventually marked as mitigated, and after 1,646 re-imports, there were 0 vulnerabilities overall.

![image](https://github.com/user-attachments/assets/6387079d-57f2-4c2d-8629-4947f5bc8d43)

That is, each new test closes all the others, even though each test has the service field specified. However, it seems that DefectDojo doesn't take this field into account.

![image](https://github.com/user-attachments/assets/55a13c9c-3035-4702-87be-370787dd1afb)

Thanks )

**Comment by manuel-sommer** [comment]
> The main issue is that vulnerabilities that haven't been reported for a long time should be closed, but with the defectDojoCloseOldFindings parameter, all vulnerabilities are being closed, as shown in the screenshot, despite it stating "only the findings for this service will be closed."
> 
> I would also like to understand how to conveniently use it in this case. As far as I understand, this situation occurs because of re-importing, not because a new engagement is created for each request.

From my point of view this is rather a DefectDojo bug than a Trivy-dojo-report-operator bug. I guess you should ask in the DefectDojo slack channel for help as from my understanding you are doing / understanding something wrong: 
https://support.defectdojo.com/en/articles/9424972-avoiding-duplicates-reimport-recurring-tests#h_15091c1779

I am unsubscribing here.

**Comment by rndmh3ro** [comment]
Yes, I don't think we can do anything here on the operator side as we're basically just using the api as-is. The same would happen if you would feed the data Directly into dojo..

**Comment by iamhalje** [comment]
here will be a continuation

https://github.com/DefectDojo/django-DefectDojo/issues/11320
